# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.


# Site settings
title: TheArgyleMVP
name: TheArgyleMVP
email: richard@masteringlync.com
location: Minneapolis, MN
company: T2M
company_url: https://t2mdev.com
github_url: https://github.com/rbrynteson
github_username:  rbrynteson
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to The Argyle MVP Website.  We hope to have all sorts of fun code, blog
  articles and much more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rbrynteson

repository: rbrynteson/rbrynteson.github.io
#url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
plugins:
  - jekyll-feed

kramdown:
  input: GFM
  enable_coderay: true
 
 # Disque
disque: theargylemvp.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them
navs:
  -
    href: /
    label: Home

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /projects
    label: Projects

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-19978686-5'  # ex. UA-72165600-X
 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
